version: '3.9'
services:
  php:
    image: php:v1
    build: ./dockerfile/php
    container_name: docker_laravel_php
    volumes:
      - ./src:/var/www/html
      - ./dockerfile/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 80:80

  mysql:
    image: mysql:8
    container_name: docker_laravel_mysql
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox

  redis:
    image: redis:7
    container_name: docker_laravel_redis
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    command: redis-server

networks:
  default:
    name: docker_laravel