version: '3.9'
services:
  php:
    image: php:v1
    build:
      context: .
      dockerfile: ./dockerfile/Dockerfile
    container_name: laravel_sandbox_php
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - '8000:8000'

  mysql:
    image: mysql:8
    container_name: laravel_sandbox_mysql
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox

  redis:
    image: redis:7
    container_name: laravel_sandbox_redis
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    command: redis-server

networks:
  default:
    name: laravel_sandbox